- name: Setup the wifi interfaces
  template: src=interfaces.j2 dest=/etc/network/interfaces

- name: Copy the dhcpd.conf
  copy: src=dhcpd.conf dest=/etc/dhcpd.conf

- name: Copy the isc-dhcp-server config
  copy: src=isc-dhcp-server dest=/etc/default/isc-dhcp-server

- name: Copy the hostapd config
  template: src=hostapd.conf.j2 dest=/etc/hostapd/hostapd.conf

- name: Setup the hostapd.conf
  copy: src=hostapd dest=/etc/default/hostapd

- name: Enable Ipv4 forwarding
  copy: src=sysctl.conf dest=/etc/sysctl.conf

- name: Copy torrc config file
  copy: src=torrc dest=/etc/tor/torrc

- name: Copy NAT forwarding rules
  copy: src=rules.v4 dest=/etc/iptables/rules.v4

- service:
    name: hostapd
    state: started

- service:
    name: isc-dhcp-server
    state: started

- service:
    name: tor
    state: started
